/**
 * Shared Stock Symbol List
 * 
 * Centralized list of 500+ largest US companies with categories
 * Used by both HomeScreen and WatchList
 */

export interface StockSymbol {
  symbol: string;
  name: string;
  category: string;
}

export function getStockSymbolList(): StockSymbol[] {
  return [
    // Technology - Mega Cap
    { symbol: 'AAPL', name: 'Apple Inc', category: 'Information Technology' },
    { symbol: 'MSFT', name: 'Microsoft Corp', category: 'Information Technology' },
    { symbol: 'GOOGL', name: 'Alphabet Inc', category: 'Information Technology' },
    { symbol: 'GOOG', name: 'Alphabet Inc Class C', category: 'Information Technology' },
    { symbol: 'AMZN', name: 'Amazon.com Inc', category: 'Information Technology' },
    { symbol: 'META', name: 'Meta Platforms', category: 'Information Technology' },
    { symbol: 'NVDA', name: 'NVIDIA Corp', category: 'Information Technology' },
    { symbol: 'TSLA', name: 'Tesla Inc', category: 'Information Technology' },
    
    // Technology - Large Cap
    { symbol: 'AVGO', name: 'Broadcom Inc', category: 'Information Technology' },
    { symbol: 'ORCL', name: 'Oracle Corp', category: 'Information Technology' },
    { symbol: 'CRM', name: 'Salesforce Inc', category: 'Information Technology' },
    { symbol: 'ADBE', name: 'Adobe Inc', category: 'Information Technology' },
    { symbol: 'CSCO', name: 'Cisco Systems', category: 'Information Technology' },
    { symbol: 'INTC', name: 'Intel Corp', category: 'Information Technology' },
    { symbol: 'AMD', name: 'Advanced Micro Devices', category: 'Information Technology' },
    { symbol: 'QCOM', name: 'QUALCOMM Inc', category: 'Information Technology' },
    { symbol: 'TXN', name: 'Texas Instruments', category: 'Information Technology' },
    { symbol: 'IBM', name: 'International Business Machines', category: 'Information Technology' },
    { symbol: 'NOW', name: 'ServiceNow Inc', category: 'Information Technology' },
    { symbol: 'INTU', name: 'Intuit Inc', category: 'Information Technology' },
    { symbol: 'AMAT', name: 'Applied Materials', category: 'Information Technology' },
    { symbol: 'MU', name: 'Micron Technology', category: 'Information Technology' },
    { symbol: 'SMCI', name: 'Super Micro Computer Inc', category: 'Information Technology' },
    { symbol: 'LRCX', name: 'Lam Research', category: 'Information Technology' },
    { symbol: 'ADI', name: 'Analog Devices', category: 'Information Technology' },
    { symbol: 'KLAC', name: 'KLA Corp', category: 'Information Technology' },
    { symbol: 'SNPS', name: 'Synopsys Inc', category: 'Information Technology' },
    { symbol: 'CDNS', name: 'Cadence Design Systems', category: 'Information Technology' },
    { symbol: 'MRVL', name: 'Marvell Technology', category: 'Information Technology' },
    { symbol: 'NXPI', name: 'NXP Semiconductors', category: 'Information Technology' },
    { symbol: 'MCHP', name: 'Microchip Technology', category: 'Information Technology' },
    { symbol: 'ON', name: 'ON Semiconductor', category: 'Information Technology' },
    { symbol: 'MPWR', name: 'Monolithic Power Systems', category: 'Information Technology' },
    { symbol: 'SWKS', name: 'Skyworks Solutions', category: 'Information Technology' },
    { symbol: 'QRVO', name: 'Qorvo Inc', category: 'Information Technology' },
    
    // Technology - Software & Cloud
    { symbol: 'PANW', name: 'Palo Alto Networks', category: 'Information Technology' },
    { symbol: 'CRWD', name: 'CrowdStrike Holdings', category: 'Information Technology' },
    { symbol: 'SNOW', name: 'Snowflake Inc', category: 'Information Technology' },
    { symbol: 'DDOG', name: 'Datadog Inc', category: 'Information Technology' },
    { symbol: 'ZS', name: 'Zscaler Inc', category: 'Information Technology' },
    { symbol: 'WDAY', name: 'Workday Inc', category: 'Information Technology' },
    { symbol: 'FTNT', name: 'Fortinet Inc', category: 'Information Technology' },
    { symbol: 'NET', name: 'Cloudflare Inc', category: 'Information Technology' },
    { symbol: 'TEAM', name: 'Atlassian Corp', category: 'Information Technology' },
    { symbol: 'HUBS', name: 'HubSpot Inc', category: 'Information Technology' },
    { symbol: 'OKTA', name: 'Okta Inc', category: 'Information Technology' },
    { symbol: 'VEEV', name: 'Veeva Systems', category: 'Information Technology' },
    { symbol: 'SPLK', name: 'Splunk Inc', category: 'Information Technology' },
    { symbol: 'ANSS', name: 'ANSYS Inc', category: 'Information Technology' },
    { symbol: 'ROP', name: 'Roper Technologies', category: 'Information Technology' },
    { symbol: 'ADSK', name: 'Autodesk Inc', category: 'Information Technology' },
    { symbol: 'TWLO', name: 'Twilio Inc', category: 'Information Technology' },
    { symbol: 'DOCU', name: 'DocuSign Inc', category: 'Information Technology' },
    { symbol: 'ZM', name: 'Zoom Video Communications', category: 'Information Technology' },
    { symbol: 'DKNG', name: 'DraftKings Inc', category: 'Information Technology' },
    { symbol: 'PLTR', name: 'Palantir Technologies', category: 'Information Technology' },
    { symbol: 'U', name: 'Unity Software', category: 'Information Technology' },
    { symbol: 'RBLX', name: 'Roblox Corp', category: 'Information Technology' },
    { symbol: 'GTLB', name: 'GitLab Inc', category: 'Information Technology' },
    { symbol: 'S', name: 'SentinelOne Inc', category: 'Information Technology' },
    
    // Technology - Hardware & Electronics
    { symbol: 'HPQ', name: 'HP Inc', category: 'Information Technology' },
    { symbol: 'HPE', name: 'Hewlett Packard Enterprise', category: 'Information Technology' },
    { symbol: 'DELL', name: 'Dell Technologies', category: 'Information Technology' },
    { symbol: 'APH', name: 'Amphenol Corp', category: 'Information Technology' },
    { symbol: 'TEL', name: 'TE Connectivity', category: 'Information Technology' },
    { symbol: 'GLW', name: 'Corning Inc', category: 'Information Technology' },
    { symbol: 'KEYS', name: 'Keysight Technologies', category: 'Information Technology' },
    { symbol: 'ZBRA', name: 'Zebra Technologies', category: 'Information Technology' },
    { symbol: 'NTAP', name: 'NetApp Inc', category: 'Information Technology' },
    { symbol: 'STX', name: 'Seagate Technology', category: 'Information Technology' },
    { symbol: 'WDC', name: 'Western Digital', category: 'Information Technology' },
    { symbol: 'ENPH', name: 'Enphase Energy', category: 'Information Technology' },
    { symbol: 'SEDG', name: 'SolarEdge Technologies', category: 'Information Technology' },
    { symbol: 'FSLR', name: 'First Solar Inc', category: 'Information Technology' },
    { symbol: 'PATH', name: 'UiPath Inc', category: 'Information Technology' },
    { symbol: 'BILL', name: 'Bill.com Holdings', category: 'Information Technology' },
    { symbol: 'ESTC', name: 'Elastic NV', category: 'Information Technology' },
    { symbol: 'CFLT', name: 'Confluent Inc', category: 'Information Technology' },
    
    // E-Commerce & Internet
    { symbol: 'SHOP', name: 'Shopify Inc', category: 'Consumer Discretionary' },
    { symbol: 'EBAY', name: 'eBay Inc', category: 'Consumer Discretionary' },
    { symbol: 'ETSY', name: 'Etsy Inc', category: 'Consumer Discretionary' },
    { symbol: 'MELI', name: 'MercadoLibre Inc', category: 'Consumer Discretionary' },
    { symbol: 'SE', name: 'Sea Ltd', category: 'Consumer Discretionary' },
    { symbol: 'BABA', name: 'Alibaba Group', category: 'Consumer Discretionary' },
    { symbol: 'JD', name: 'JD.com Inc', category: 'Consumer Discretionary' },
    { symbol: 'PDD', name: 'PDD Holdings', category: 'Consumer Discretionary' },
    
    // Streaming & Media
    { symbol: 'NFLX', name: 'Netflix Inc', category: 'Communication Services' },
    { symbol: 'DIS', name: 'Walt Disney Co', category: 'Communication Services' },
    { symbol: 'WBD', name: 'Warner Bros Discovery', category: 'Communication Services' },
    { symbol: 'PARA', name: 'Paramount Global', category: 'Communication Services' },
    { symbol: 'ROKU', name: 'Roku Inc', category: 'Communication Services' },
    { symbol: 'SPOT', name: 'Spotify Technology', category: 'Communication Services' },
    { symbol: 'MTCH', name: 'Match Group', category: 'Communication Services' },
    { symbol: 'PINS', name: 'Pinterest Inc', category: 'Communication Services' },
    { symbol: 'SNAP', name: 'Snap Inc', category: 'Communication Services' },
    { symbol: 'RDDT', name: 'Reddit Inc', category: 'Communication Services' },
    
    // Gaming
    { symbol: 'EA', name: 'Electronic Arts', category: 'Communication Services' },
    { symbol: 'TTWO', name: 'Take-Two Interactive', category: 'Communication Services' },
    { symbol: 'ATVI', name: 'Activision Blizzard', category: 'Communication Services' },
    { symbol: 'AMC', name: 'AMC Entertainment', category: 'Communication Services' },
    { symbol: 'NWSA', name: 'News Corp', category: 'Communication Services' },
    { symbol: 'FOXA', name: 'Fox Corp', category: 'Communication Services' },
    { symbol: 'OMC', name: 'Omnicom Group', category: 'Communication Services' },
    { symbol: 'IPG', name: 'Interpublic Group', category: 'Communication Services' },
    
    // Finance - Mega Banks
    { symbol: 'JPM', name: 'JPMorgan Chase & Co', category: 'Financials' },
    { symbol: 'BAC', name: 'Bank of America Corp', category: 'Financials' },
    { symbol: 'WFC', name: 'Wells Fargo & Co', category: 'Financials' },
    { symbol: 'C', name: 'Citigroup Inc', category: 'Financials' },
    { symbol: 'GS', name: 'Goldman Sachs Group', category: 'Financials' },
    { symbol: 'MS', name: 'Morgan Stanley', category: 'Financials' },
    { symbol: 'BLK', name: 'BlackRock Inc', category: 'Financials' },
    { symbol: 'SCHW', name: 'Charles Schwab Corp', category: 'Financials' },
    { symbol: 'USB', name: 'U.S. Bancorp', category: 'Financials' },
    { symbol: 'PNC', name: 'PNC Financial Services', category: 'Financials' },
    { symbol: 'TFC', name: 'Truist Financial Corp', category: 'Financials' },
    { symbol: 'BK', name: 'Bank of New York Mellon', category: 'Financials' },
    { symbol: 'STT', name: 'State Street Corp', category: 'Financials' },
    { symbol: 'COF', name: 'Capital One Financial', category: 'Financials' },
    { symbol: 'DFS', name: 'Discover Financial Services', category: 'Financials' },
    { symbol: 'AXP', name: 'American Express Co', category: 'Financials' },
    
    // Finance - Regional Banks
    { symbol: 'RF', name: 'Regions Financial', category: 'Financials' },
    { symbol: 'CFG', name: 'Citizens Financial Group', category: 'Financials' },
    { symbol: 'KEY', name: 'KeyCorp', category: 'Financials' },
    { symbol: 'FITB', name: 'Fifth Third Bancorp', category: 'Financials' },
    { symbol: 'HBAN', name: 'Huntington Bancshares', category: 'Financials' },
    { symbol: 'MTB', name: 'M&T Bank Corp', category: 'Financials' },
    { symbol: 'ZION', name: 'Zions Bancorp', category: 'Financials' },
    { symbol: 'WBS', name: 'Webster Financial', category: 'Financials' },
    { symbol: 'FHN', name: 'First Horizon Corp', category: 'Financials' },
    { symbol: 'EWBC', name: 'East West Bancorp', category: 'Financials' },
    { symbol: 'PNFP', name: 'Pinnacle Financial', category: 'Financials' },
    { symbol: 'SNV', name: 'Synovus Financial', category: 'Financials' },
    { symbol: 'WAL', name: 'Western Alliance Bancorp', category: 'Financials' },
    
    // Finance - Investment & Insurance
    { symbol: 'SPGI', name: 'S&P Global Inc', category: 'Financials' },
    { symbol: 'MCO', name: 'Moody\'s Corp', category: 'Financials' },
    { symbol: 'CME', name: 'CME Group Inc', category: 'Financials' },
    { symbol: 'ICE', name: 'Intercontinental Exchange', category: 'Financials' },
    { symbol: 'MSCI', name: 'MSCI Inc', category: 'Financials' },
    { symbol: 'NDAQ', name: 'Nasdaq Inc', category: 'Financials' },
    { symbol: 'CBOE', name: 'Cboe Global Markets', category: 'Financials' },
    { symbol: 'AMP', name: 'Ameriprise Financial', category: 'Financials' },
    { symbol: 'TROW', name: 'T. Rowe Price Group', category: 'Financials' },
    { symbol: 'BEN', name: 'Franklin Resources', category: 'Financials' },
    { symbol: 'IVZ', name: 'Invesco Ltd', category: 'Financials' },
    { symbol: 'NTRS', name: 'Northern Trust Corp', category: 'Financials' },
    
    // Finance - Payment Processors
    { symbol: 'V', name: 'Visa Inc', category: 'Financials' },
    { symbol: 'MA', name: 'Mastercard Inc', category: 'Financials' },
    { symbol: 'PYPL', name: 'PayPal Holdings', category: 'Financials' },
    { symbol: 'SQ', name: 'Block Inc', category: 'Financials' },
    { symbol: 'FIS', name: 'Fidelity National Info Services', category: 'Financials' },
    { symbol: 'FISV', name: 'Fiserv Inc', category: 'Financials' },
    { symbol: 'ADP', name: 'Automatic Data Processing', category: 'Financials' },
    { symbol: 'PAYX', name: 'Paychex Inc', category: 'Financials' },
    { symbol: 'FLT', name: 'FleetCor Technologies', category: 'Financials' },
    { symbol: 'GPN', name: 'Global Payments Inc', category: 'Financials' },
    
    // Finance - Fintech
    { symbol: 'COIN', name: 'Coinbase Global', category: 'Financials' },
    { symbol: 'SOFI', name: 'SoFi Technologies', category: 'Financials' },
    { symbol: 'HOOD', name: 'Robinhood Markets', category: 'Financials' },
    { symbol: 'AFRM', name: 'Affirm Holdings', category: 'Financials' },
    { symbol: 'UPST', name: 'Upstart Holdings', category: 'Financials' },
    { symbol: 'LC', name: 'LendingClub Corp', category: 'Financials' },
    { symbol: 'RJF', name: 'Raymond James Financial', category: 'Financials' },
    { symbol: 'SIVB', name: 'SVB Financial Group', category: 'Financials' },
    { symbol: 'CMA', name: 'Comerica Inc', category: 'Financials' },
    { symbol: 'FCNCA', name: 'First Citizens BancShares', category: 'Financials' },
    { symbol: 'ALLY', name: 'Ally Financial', category: 'Financials' },
    { symbol: 'SYF', name: 'Synchrony Financial', category: 'Financials' },
    
    // Insurance
    { symbol: 'BRK.B', name: 'Berkshire Hathaway', category: 'Financials' },
    { symbol: 'PGR', name: 'Progressive Corp', category: 'Financials' },
    { symbol: 'ALL', name: 'Allstate Corp', category: 'Financials' },
    { symbol: 'TRV', name: 'Travelers Companies', category: 'Financials' },
    { symbol: 'AIG', name: 'American International Group', category: 'Financials' },
    { symbol: 'MET', name: 'MetLife Inc', category: 'Financials' },
    { symbol: 'PRU', name: 'Prudential Financial', category: 'Financials' },
    { symbol: 'AFL', name: 'Aflac Inc', category: 'Financials' },
    { symbol: 'AJG', name: 'Arthur J Gallagher', category: 'Financials' },
    { symbol: 'MMC', name: 'Marsh & McLennan', category: 'Financials' },
    { symbol: 'AON', name: 'Aon PLC', category: 'Financials' },
    { symbol: 'WRB', name: 'W.R. Berkley Corp', category: 'Financials' },
    { symbol: 'CB', name: 'Chubb Ltd', category: 'Financials' },
    { symbol: 'HIG', name: 'Hartford Financial Services', category: 'Financials' },
    { symbol: 'L', name: 'Loews Corp', category: 'Financials' },
    { symbol: 'RLI', name: 'RLI Corp', category: 'Financials' },
    { symbol: 'GL', name: 'Globe Life Inc', category: 'Financials' },
    { symbol: 'CINF', name: 'Cincinnati Financial', category: 'Financials' },
    
    // Healthcare - Pharma
    { symbol: 'JNJ', name: 'Johnson & Johnson', category: 'Health Care' },
    { symbol: 'UNH', name: 'UnitedHealth Group', category: 'Health Care' },
    { symbol: 'LLY', name: 'Eli Lilly and Co', category: 'Health Care' },
    { symbol: 'ABBV', name: 'AbbVie Inc', category: 'Health Care' },
    { symbol: 'PFE', name: 'Pfizer Inc', category: 'Health Care' },
    { symbol: 'MRK', name: 'Merck & Co', category: 'Health Care' },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific', category: 'Health Care' },
    { symbol: 'ABT', name: 'Abbott Laboratories', category: 'Health Care' },
    { symbol: 'DHR', name: 'Danaher Corp', category: 'Health Care' },
    { symbol: 'AMGN', name: 'Amgen Inc', category: 'Health Care' },
    { symbol: 'GILD', name: 'Gilead Sciences', category: 'Health Care' },
    { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', category: 'Health Care' },
    { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', category: 'Health Care' },
    { symbol: 'BMY', name: 'Bristol Myers Squibb', category: 'Health Care' },
    { symbol: 'BIIB', name: 'Biogen Inc', category: 'Health Care' },
    { symbol: 'MRNA', name: 'Moderna Inc', category: 'Health Care' },
    { symbol: 'BNTX', name: 'BioNTech SE', category: 'Health Care' },
    { symbol: 'ZTS', name: 'Zoetis Inc', category: 'Health Care' },
    { symbol: 'BSX', name: 'Boston Scientific', category: 'Health Care' },
    { symbol: 'SYK', name: 'Stryker Corp', category: 'Health Care' },
    { symbol: 'MDT', name: 'Medtronic PLC', category: 'Health Care' },
    { symbol: 'ISRG', name: 'Intuitive Surgical', category: 'Health Care' },
    { symbol: 'EW', name: 'Edwards Lifesciences', category: 'Health Care' },
    { symbol: 'IDXX', name: 'IDEXX Laboratories', category: 'Health Care' },
    { symbol: 'A', name: 'Agilent Technologies', category: 'Health Care' },
    { symbol: 'IQV', name: 'IQVIA Holdings', category: 'Health Care' },
    { symbol: 'DXCM', name: 'DexCom Inc', category: 'Health Care' },
    { symbol: 'ALGN', name: 'Align Technology', category: 'Health Care' },
    { symbol: 'HOLX', name: 'Hologic Inc', category: 'Health Care' },
    { symbol: 'BAX', name: 'Baxter International', category: 'Health Care' },
    { symbol: 'BDX', name: 'Becton Dickinson', category: 'Health Care' },
    { symbol: 'RMD', name: 'ResMed Inc', category: 'Health Care' },
    { symbol: 'WAT', name: 'Waters Corp', category: 'Health Care' },
    { symbol: 'TECH', name: 'Bio-Techne Corp', category: 'Health Care' },
    { symbol: 'PKI', name: 'PerkinElmer Inc', category: 'Health Care' },
    { symbol: 'ILMN', name: 'Illumina Inc', category: 'Health Care' },
    { symbol: 'EXAS', name: 'Exact Sciences', category: 'Health Care' },
    { symbol: 'INCY', name: 'Incyte Corp', category: 'Health Care' },
    { symbol: 'SGEN', name: 'Seagen Inc', category: 'Health Care' },
    { symbol: 'ALNY', name: 'Alnylam Pharmaceuticals', category: 'Health Care' },
    { symbol: 'NBIX', name: 'Neurocrine Biosciences', category: 'Health Care' },
    { symbol: 'VTRS', name: 'Viatris Inc', category: 'Health Care' },
    { symbol: 'ZBH', name: 'Zimmer Biomet Holdings', category: 'Health Care' },
    
    // Healthcare - Services & Managed Care
    { symbol: 'CVS', name: 'CVS Health Corp', category: 'Health Care' },
    { symbol: 'CI', name: 'Cigna Group', category: 'Health Care' },
    { symbol: 'ELV', name: 'Elevance Health', category: 'Health Care' },
    { symbol: 'HUM', name: 'Humana Inc', category: 'Health Care' },
    { symbol: 'CNC', name: 'Centene Corp', category: 'Health Care' },
    { symbol: 'MOH', name: 'Molina Healthcare', category: 'Health Care' },
    { symbol: 'HCA', name: 'HCA Healthcare', category: 'Health Care' },
    { symbol: 'UHS', name: 'Universal Health Services', category: 'Health Care' },
    { symbol: 'DVA', name: 'DaVita Inc', category: 'Health Care' },
    { symbol: 'HSIC', name: 'Henry Schein', category: 'Health Care' },
    { symbol: 'CAH', name: 'Cardinal Health', category: 'Health Care' },
    { symbol: 'MCK', name: 'McKesson Corp', category: 'Health Care' },
    { symbol: 'COR', name: 'Cencora Inc', category: 'Health Care' },
    
    // Consumer - Retail
    { symbol: 'WMT', name: 'Walmart Inc', category: 'Consumer Discretionary' },
    { symbol: 'COST', name: 'Costco Wholesale', category: 'Consumer Discretionary' },
    { symbol: 'HD', name: 'Home Depot Inc', category: 'Consumer Discretionary' },
    { symbol: 'LOW', name: 'Lowe\'s Companies', category: 'Consumer Discretionary' },
    { symbol: 'TGT', name: 'Target Corp', category: 'Consumer Discretionary' },
    { symbol: 'TJX', name: 'TJX Companies', category: 'Consumer Discretionary' },
    { symbol: 'ROST', name: 'Ross Stores', category: 'Consumer Discretionary' },
    { symbol: 'DG', name: 'Dollar General', category: 'Consumer Discretionary' },
    { symbol: 'DLTR', name: 'Dollar Tree', category: 'Consumer Discretionary' },
    { symbol: 'BBY', name: 'Best Buy Co', category: 'Consumer Discretionary' },
    { symbol: 'ULTA', name: 'Ulta Beauty', category: 'Consumer Discretionary' },
    { symbol: 'FIVE', name: 'Five Below', category: 'Consumer Discretionary' },
    { symbol: 'DKS', name: 'Dick\'s Sporting Goods', category: 'Consumer Discretionary' },
    { symbol: 'AZO', name: 'AutoZone Inc', category: 'Consumer Discretionary' },
    { symbol: 'ORLY', name: 'O\'Reilly Automotive', category: 'Consumer Discretionary' },
    { symbol: 'AAP', name: 'Advance Auto Parts', category: 'Consumer Discretionary' },
    { symbol: 'GPC', name: 'Genuine Parts Co', category: 'Consumer Discretionary' },
    { symbol: 'KSS', name: 'Kohl\'s Corp', category: 'Consumer Discretionary' },
    { symbol: 'M', name: 'Macy\'s Inc', category: 'Consumer Discretionary' },
    { symbol: 'JWN', name: 'Nordstrom Inc', category: 'Consumer Discretionary' },
    { symbol: 'TSCO', name: 'Tractor Supply Co', category: 'Consumer Discretionary' },
    { symbol: 'AN', name: 'AutoNation Inc', category: 'Consumer Discretionary' },
    { symbol: 'PAG', name: 'Penske Automotive Group', category: 'Consumer Discretionary' },
    { symbol: 'LAD', name: 'Lithia Motors', category: 'Consumer Discretionary' },
    { symbol: 'PLAY', name: 'Dave & Buster\'s Entertainment', category: 'Consumer Discretionary' },
    
    // Consumer - Apparel & Footwear
    { symbol: 'NKE', name: 'Nike Inc', category: 'Consumer Discretionary' },
    { symbol: 'LULU', name: 'Lululemon Athletica', category: 'Consumer Discretionary' },
    { symbol: 'UAA', name: 'Under Armour', category: 'Consumer Discretionary' },
    { symbol: 'CROX', name: 'Crocs Inc', category: 'Consumer Discretionary' },
    { symbol: 'DECK', name: 'Deckers Outdoor', category: 'Consumer Discretionary' },
    { symbol: 'VFC', name: 'VF Corp', category: 'Consumer Discretionary' },
    { symbol: 'PVH', name: 'PVH Corp', category: 'Consumer Discretionary' },
    { symbol: 'RL', name: 'Ralph Lauren Corp', category: 'Consumer Discretionary' },
    { symbol: 'TPR', name: 'Tapestry Inc', category: 'Consumer Discretionary' },
    { symbol: 'CPRI', name: 'Capri Holdings', category: 'Consumer Discretionary' },
    { symbol: 'HBI', name: 'Hanesbrands Inc', category: 'Consumer Discretionary' },
    
    // Consumer - Food & Beverage
    { symbol: 'PEP', name: 'PepsiCo Inc', category: 'Consumer Staples' },
    { symbol: 'KO', name: 'Coca-Cola Co', category: 'Consumer Staples' },
    { symbol: 'MDLZ', name: 'Mondelez International', category: 'Consumer Staples' },
    { symbol: 'GIS', name: 'General Mills', category: 'Consumer Staples' },
    { symbol: 'K', name: 'Kellogg Co', category: 'Consumer Staples' },
    { symbol: 'KHC', name: 'Kraft Heinz Co', category: 'Consumer Staples' },
    { symbol: 'HSY', name: 'Hershey Co', category: 'Consumer Staples' },
    { symbol: 'CAG', name: 'Conagra Brands', category: 'Consumer Staples' },
    { symbol: 'CPB', name: 'Campbell Soup Co', category: 'Consumer Staples' },
    { symbol: 'HRL', name: 'Hormel Foods', category: 'Consumer Staples' },
    { symbol: 'SJM', name: 'JM Smucker Co', category: 'Consumer Staples' },
    { symbol: 'MKC', name: 'McCormick & Co', category: 'Consumer Staples' },
    { symbol: 'TSN', name: 'Tyson Foods', category: 'Consumer Staples' },
    { symbol: 'BF.B', name: 'Brown-Forman Corp', category: 'Consumer Staples' },
    { symbol: 'STZ', name: 'Constellation Brands', category: 'Consumer Staples' },
    { symbol: 'TAP', name: 'Molson Coors Beverage', category: 'Consumer Staples' },
    { symbol: 'SAM', name: 'Boston Beer Co', category: 'Consumer Staples' },
    { symbol: 'CELH', name: 'Celsius Holdings', category: 'Consumer Staples' },
    { symbol: 'MNST', name: 'Monster Beverage', category: 'Consumer Staples' },
    
    // Consumer - Household & Personal Care
    { symbol: 'PG', name: 'Procter & Gamble', category: 'Consumer Staples' },
    { symbol: 'CL', name: 'Colgate-Palmolive Co', category: 'Consumer Staples' },
    { symbol: 'KMB', name: 'Kimberly-Clark Corp', category: 'Consumer Staples' },
    { symbol: 'CLX', name: 'Clorox Co', category: 'Consumer Staples' },
    { symbol: 'CHD', name: 'Church & Dwight', category: 'Consumer Staples' },
    { symbol: 'EL', name: 'Estee Lauder Companies', category: 'Consumer Staples' },
    { symbol: 'NWL', name: 'Newell Brands', category: 'Consumer Staples' },
    
    // Consumer - Tobacco
    { symbol: 'PM', name: 'Philip Morris International', category: 'Consumer Staples' },
    { symbol: 'MO', name: 'Altria Group', category: 'Consumer Staples' },
    { symbol: 'BTI', name: 'British American Tobacco', category: 'Consumer Staples' },
    { symbol: 'COKE', name: 'Coca-Cola Consolidated', category: 'Consumer Staples' },
    { symbol: 'KDP', name: 'Keurig Dr Pepper', category: 'Consumer Staples' },
    { symbol: 'BG', name: 'Bunge Global SA', category: 'Consumer Staples' },
    { symbol: 'ADM', name: 'Archer-Daniels-Midland', category: 'Consumer Staples' },
    
    // Restaurants
    { symbol: 'MCD', name: 'McDonald\'s Corp', category: 'Consumer Discretionary' },
    { symbol: 'SBUX', name: 'Starbucks Corp', category: 'Consumer Discretionary' },
    { symbol: 'CMG', name: 'Chipotle Mexican Grill', category: 'Consumer Discretionary' },
    { symbol: 'YUM', name: 'Yum! Brands', category: 'Consumer Discretionary' },
    { symbol: 'QSR', name: 'Restaurant Brands International', category: 'Consumer Discretionary' },
    { symbol: 'DPZ', name: 'Domino\'s Pizza', category: 'Consumer Discretionary' },
    { symbol: 'WING', name: 'Wingstop Inc', category: 'Consumer Discretionary' },
    { symbol: 'CAVA', name: 'CAVA Group', category: 'Consumer Discretionary' },
    { symbol: 'SHAK', name: 'Shake Shack', category: 'Consumer Discretionary' },
    { symbol: 'TXRH', name: 'Texas Roadhouse', category: 'Consumer Discretionary' },
    { symbol: 'DRI', name: 'Darden Restaurants', category: 'Consumer Discretionary' },
    { symbol: 'EAT', name: 'Brinker International', category: 'Consumer Discretionary' },
    { symbol: 'BLMN', name: 'Bloomin\' Brands', category: 'Consumer Discretionary' },
    { symbol: 'CAKE', name: 'Cheesecake Factory', category: 'Consumer Discretionary' },
    
    // Energy - Integrated
    { symbol: 'XOM', name: 'Exxon Mobil Corp', category: 'Energy' },
    { symbol: 'CVX', name: 'Chevron Corp', category: 'Energy' },
    { symbol: 'COP', name: 'ConocoPhillips', category: 'Energy' },
    { symbol: 'SLB', name: 'Schlumberger NV', category: 'Energy' },
    { symbol: 'EOG', name: 'EOG Resources', category: 'Energy' },
    { symbol: 'PXD', name: 'Pioneer Natural Resources', category: 'Energy' },
    { symbol: 'MPC', name: 'Marathon Petroleum', category: 'Energy' },
    { symbol: 'VLO', name: 'Valero Energy', category: 'Energy' },
    { symbol: 'PSX', name: 'Phillips 66', category: 'Energy' },
    { symbol: 'OXY', name: 'Occidental Petroleum', category: 'Energy' },
    { symbol: 'HAL', name: 'Halliburton Co', category: 'Energy' },
    { symbol: 'BKR', name: 'Baker Hughes Co', category: 'Energy' },
    { symbol: 'DVN', name: 'Devon Energy', category: 'Energy' },
    { symbol: 'FANG', name: 'Diamondback Energy', category: 'Energy' },
    { symbol: 'HES', name: 'Hess Corp', category: 'Energy' },
    { symbol: 'MRO', name: 'Marathon Oil', category: 'Energy' },
    { symbol: 'OVV', name: 'Ovintiv Inc', category: 'Energy' },
    { symbol: 'APA', name: 'APA Corp', category: 'Energy' },
    { symbol: 'CTRA', name: 'Coterra Energy', category: 'Energy' },
    { symbol: 'EQT', name: 'EQT Corp', category: 'Energy' },
    { symbol: 'NOV', name: 'NOV Inc', category: 'Energy' },
    { symbol: 'FTI', name: 'TechnipFMC PLC', category: 'Energy' },
    
    // Utilities
    { symbol: 'NEE', name: 'NextEra Energy', category: 'Utilities' },
    { symbol: 'DUK', name: 'Duke Energy', category: 'Utilities' },
    { symbol: 'SO', name: 'Southern Co', category: 'Utilities' },
    { symbol: 'D', name: 'Dominion Energy', category: 'Utilities' },
    { symbol: 'AEP', name: 'American Electric Power', category: 'Utilities' },
    { symbol: 'EXC', name: 'Exelon Corp', category: 'Utilities' },
    { symbol: 'SRE', name: 'Sempra Energy', category: 'Utilities' },
    { symbol: 'XEL', name: 'Xcel Energy', category: 'Utilities' },
    { symbol: 'ED', name: 'Consolidated Edison', category: 'Utilities' },
    { symbol: 'WEC', name: 'WEC Energy Group', category: 'Utilities' },
    { symbol: 'AWK', name: 'American Water Works', category: 'Utilities' },
    { symbol: 'ES', name: 'Eversource Energy', category: 'Utilities' },
    { symbol: 'FE', name: 'FirstEnergy Corp', category: 'Utilities' },
    { symbol: 'ETR', name: 'Entergy Corp', category: 'Utilities' },
    { symbol: 'PPL', name: 'PPL Corp', category: 'Utilities' },
    { symbol: 'CMS', name: 'CMS Energy', category: 'Utilities' },
    { symbol: 'PEG', name: 'Public Service Enterprise', category: 'Utilities' },
    { symbol: 'DTE', name: 'DTE Energy', category: 'Utilities' },
    { symbol: 'AEE', name: 'Ameren Corp', category: 'Utilities' },
    { symbol: 'CNP', name: 'CenterPoint Energy', category: 'Utilities' },
    
    // Industrial - Aerospace & Defense
    { symbol: 'BA', name: 'Boeing Co', category: 'Industrials' },
    { symbol: 'RTX', name: 'RTX Corp', category: 'Industrials' },
    { symbol: 'LMT', name: 'Lockheed Martin', category: 'Industrials' },
    { symbol: 'GD', name: 'General Dynamics', category: 'Industrials' },
    { symbol: 'NOC', name: 'Northrop Grumman', category: 'Industrials' },
    { symbol: 'HWM', name: 'Howmet Aerospace', category: 'Industrials' },
    { symbol: 'TDG', name: 'TransDigm Group', category: 'Industrials' },
    { symbol: 'HEI', name: 'HEICO Corp', category: 'Industrials' },
    { symbol: 'TXT', name: 'Textron Inc', category: 'Industrials' },
    
    // Industrial - Machinery & Equipment
    { symbol: 'CAT', name: 'Caterpillar Inc', category: 'Industrials' },
    { symbol: 'DE', name: 'Deere & Co', category: 'Industrials' },
    { symbol: 'ITW', name: 'Illinois Tool Works', category: 'Industrials' },
    { symbol: 'EMR', name: 'Emerson Electric', category: 'Industrials' },
    { symbol: 'ETN', name: 'Eaton Corp', category: 'Industrials' },
    { symbol: 'PH', name: 'Parker-Hannifin', category: 'Industrials' },
    { symbol: 'CMI', name: 'Cummins Inc', category: 'Industrials' },
    { symbol: 'ROK', name: 'Rockwell Automation', category: 'Industrials' },
    { symbol: 'PCAR', name: 'PACCAR Inc', category: 'Industrials' },
    { symbol: 'IR', name: 'Ingersoll Rand', category: 'Industrials' },
    { symbol: 'OTIS', name: 'Otis Worldwide', category: 'Industrials' },
    { symbol: 'CARR', name: 'Carrier Global', category: 'Industrials' },
    { symbol: 'JCI', name: 'Johnson Controls', category: 'Industrials' },
    { symbol: 'GWW', name: 'W.W. Grainger', category: 'Industrials' },
    { symbol: 'FAST', name: 'Fastenal Co', category: 'Industrials' },
    { symbol: 'VMC', name: 'Vulcan Materials', category: 'Industrials' },
    { symbol: 'MLM', name: 'Martin Marietta Materials', category: 'Industrials' },
    { symbol: 'GNRC', name: 'Generac Holdings', category: 'Industrials' },
    { symbol: 'ODFL', name: 'Old Dominion Freight Line', category: 'Industrials' },
    { symbol: 'JBHT', name: 'JB Hunt Transport Services', category: 'Industrials' },
    { symbol: 'WAB', name: 'Westinghouse Air Brake Technologies', category: 'Industrials' },
    { symbol: 'URI', name: 'United Rentals', category: 'Industrials' },
    { symbol: 'PWR', name: 'Quanta Services', category: 'Industrials' },
    { symbol: 'J', name: 'Jacobs Solutions', category: 'Industrials' },
    
    // Industrial - Conglomerate
    { symbol: 'GE', name: 'General Electric', category: 'Industrials' },
    { symbol: 'HON', name: 'Honeywell International', category: 'Industrials' },
    { symbol: 'MMM', name: '3M Co', category: 'Industrials' },
    
    // Transportation & Logistics
    { symbol: 'UPS', name: 'United Parcel Service', category: 'Industrials' },
    { symbol: 'FDX', name: 'FedEx Corp', category: 'Industrials' },
    { symbol: 'UBER', name: 'Uber Technologies', category: 'Industrials' },
    { symbol: 'LYFT', name: 'Lyft Inc', category: 'Industrials' },
    { symbol: 'CSX', name: 'CSX Corp', category: 'Industrials' },
    { symbol: 'UNP', name: 'Union Pacific', category: 'Industrials' },
    { symbol: 'NSC', name: 'Norfolk Southern', category: 'Industrials' },
    { symbol: 'JBHT', name: 'JB Hunt Transport', category: 'Industrials' },
    { symbol: 'CHRW', name: 'CH Robinson Worldwide', category: 'Industrials' },
    { symbol: 'EXPD', name: 'Expeditors International', category: 'Industrials' },
    { symbol: 'XPO', name: 'XPO Logistics', category: 'Industrials' },
    { symbol: 'R', name: 'Ryder System', category: 'Industrials' },
    
    // Airlines
    { symbol: 'DAL', name: 'Delta Air Lines', category: 'Industrials' },
    { symbol: 'UAL', name: 'United Airlines Holdings', category: 'Industrials' },
    { symbol: 'AAL', name: 'American Airlines Group', category: 'Industrials' },
    { symbol: 'LUV', name: 'Southwest Airlines', category: 'Industrials' },
    { symbol: 'ALK', name: 'Alaska Air Group', category: 'Industrials' },
    { symbol: 'JBLU', name: 'JetBlue Airways', category: 'Industrials' },
    { symbol: 'SAVE', name: 'Spirit Airlines', category: 'Industrials' },
    
    // Automotive
    { symbol: 'GM', name: 'General Motors Co', category: 'Consumer Discretionary' },
    { symbol: 'F', name: 'Ford Motor Co', category: 'Consumer Discretionary' },
    { symbol: 'RIVN', name: 'Rivian Automotive', category: 'Consumer Discretionary' },
    { symbol: 'LCID', name: 'Lucid Group', category: 'Consumer Discretionary' },
    { symbol: 'NIO', name: 'NIO Inc', category: 'Consumer Discretionary' },
    { symbol: 'XPEV', name: 'XPeng Inc', category: 'Consumer Discretionary' },
    { symbol: 'LI', name: 'Li Auto Inc', category: 'Consumer Discretionary' },
    
    // Telecom
    { symbol: 'T', name: 'AT&T Inc', category: 'Communication Services' },
    { symbol: 'VZ', name: 'Verizon Communications', category: 'Communication Services' },
    { symbol: 'TMUS', name: 'T-Mobile US', category: 'Communication Services' },
    { symbol: 'CMCSA', name: 'Comcast Corp', category: 'Communication Services' },
    { symbol: 'CHTR', name: 'Charter Communications', category: 'Communication Services' },
    
    // Travel & Leisure
    { symbol: 'ABNB', name: 'Airbnb Inc', category: 'Consumer Discretionary' },
    { symbol: 'BKNG', name: 'Booking Holdings', category: 'Consumer Discretionary' },
    { symbol: 'EXPE', name: 'Expedia Group', category: 'Consumer Discretionary' },
    { symbol: 'MAR', name: 'Marriott International', category: 'Consumer Discretionary' },
    { symbol: 'HLT', name: 'Hilton Worldwide Holdings', category: 'Consumer Discretionary' },
    { symbol: 'H', name: 'Hyatt Hotels', category: 'Consumer Discretionary' },
    { symbol: 'IHG', name: 'InterContinental Hotels', category: 'Consumer Discretionary' },
    { symbol: 'RCL', name: 'Royal Caribbean Cruises', category: 'Consumer Discretionary' },
    { symbol: 'CCL', name: 'Carnival Corp', category: 'Consumer Discretionary' },
    { symbol: 'NCLH', name: 'Norwegian Cruise Line', category: 'Consumer Discretionary' },
    { symbol: 'MGM', name: 'MGM Resorts International', category: 'Consumer Discretionary' },
    { symbol: 'WYNN', name: 'Wynn Resorts', category: 'Consumer Discretionary' },
    { symbol: 'LVS', name: 'Las Vegas Sands', category: 'Consumer Discretionary' },
    { symbol: 'CZR', name: 'Caesars Entertainment', category: 'Consumer Discretionary' },
    { symbol: 'PENN', name: 'Penn Entertainment', category: 'Consumer Discretionary' },
    
    // Real Estate - REITs
    { symbol: 'AMT', name: 'American Tower Corp', category: 'Real Estate' },
    { symbol: 'PLD', name: 'Prologis Inc', category: 'Real Estate' },
    { symbol: 'CCI', name: 'Crown Castle Inc', category: 'Real Estate' },
    { symbol: 'EQIX', name: 'Equinix Inc', category: 'Real Estate' },
    { symbol: 'PSA', name: 'Public Storage', category: 'Real Estate' },
    { symbol: 'SPG', name: 'Simon Property Group', category: 'Real Estate' },
    { symbol: 'O', name: 'Realty Income Corp', category: 'Real Estate' },
    { symbol: 'DLR', name: 'Digital Realty Trust', category: 'Real Estate' },
    { symbol: 'WELL', name: 'Welltower Inc', category: 'Real Estate' },
    { symbol: 'AVB', name: 'AvalonBay Communities', category: 'Real Estate' },
    { symbol: 'EQR', name: 'Equity Residential', category: 'Real Estate' },
    { symbol: 'VTR', name: 'Ventas Inc', category: 'Real Estate' },
    { symbol: 'ARE', name: 'Alexandria Real Estate', category: 'Real Estate' },
    { symbol: 'SBAC', name: 'SBA Communications', category: 'Real Estate' },
    { symbol: 'INVH', name: 'Invitation Homes', category: 'Real Estate' },
    { symbol: 'MAA', name: 'Mid-America Apartment', category: 'Real Estate' },
    { symbol: 'ESS', name: 'Essex Property Trust', category: 'Real Estate' },
    { symbol: 'KIM', name: 'Kimco Realty', category: 'Real Estate' },
    { symbol: 'REG', name: 'Regency Centers', category: 'Real Estate' },
    { symbol: 'BXP', name: 'Boston Properties', category: 'Real Estate' },
    { symbol: 'VNO', name: 'Vornado Realty Trust', category: 'Real Estate' },
    { symbol: 'SLG', name: 'SL Green Realty', category: 'Real Estate' },
    
    // Materials - Chemicals
    { symbol: 'LIN', name: 'Linde PLC', category: 'Materials' },
    { symbol: 'APD', name: 'Air Products & Chemicals', category: 'Materials' },
    { symbol: 'SHW', name: 'Sherwin-Williams', category: 'Materials' },
    { symbol: 'ECL', name: 'Ecolab Inc', category: 'Materials' },
    { symbol: 'DD', name: 'DuPont de Nemours', category: 'Materials' },
    { symbol: 'DOW', name: 'Dow Inc', category: 'Materials' },
    { symbol: 'PPG', name: 'PPG Industries', category: 'Materials' },
    { symbol: 'LYB', name: 'LyondellBasell Industries', category: 'Materials' },
    { symbol: 'CE', name: 'Celanese Corp', category: 'Materials' },
    { symbol: 'ALB', name: 'Albemarle Corp', category: 'Materials' },
    { symbol: 'EMN', name: 'Eastman Chemical', category: 'Materials' },
    { symbol: 'FMC', name: 'FMC Corp', category: 'Materials' },
    { symbol: 'IFF', name: 'International Flavors & Fragrances', category: 'Materials' },
    
    // Materials - Metals & Mining
    { symbol: 'NUE', name: 'Nucor Corp', category: 'Materials' },
    { symbol: 'FCX', name: 'Freeport-McMoRan', category: 'Materials' },
    { symbol: 'NEM', name: 'Newmont Corp', category: 'Materials' },
    { symbol: 'GOLD', name: 'Barrick Gold Corp', category: 'Materials' },
    { symbol: 'STLD', name: 'Steel Dynamics', category: 'Materials' },
    { symbol: 'RS', name: 'Reliance Steel & Aluminum', category: 'Materials' },
    { symbol: 'AA', name: 'Alcoa Corp', category: 'Materials' },
    { symbol: 'MP', name: 'MP Materials', category: 'Materials' },
    
    // Materials - Packaging & Containers
    { symbol: 'PKG', name: 'Packaging Corp of America', category: 'Materials' },
    { symbol: 'BALL', name: 'Ball Corp', category: 'Materials' },
    { symbol: 'AVY', name: 'Avery Dennison', category: 'Materials' },
    { symbol: 'SEE', name: 'Sealed Air', category: 'Materials' },
    { symbol: 'WRK', name: 'WestRock Co', category: 'Materials' },
    { symbol: 'IP', name: 'International Paper', category: 'Materials' },
    { symbol: 'CCK', name: 'Crown Holdings', category: 'Materials' },
    { symbol: 'AMCR', name: 'Amcor PLC', category: 'Materials' },
    { symbol: 'OLN', name: 'Olin Corp', category: 'Materials' },
  ];
}
